language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
  yarn: true
before_install:
  - echo $PWD&&ls
  - chmod -R +x travis
  - (cd travis && npm install && node travis)
after_success:
  - cd travis
  - node travis success
  - echo "-----BEGIN RSA PRIVATE KEY-----" > sshkey
  - echo $sshkey >> sshkey
  - echo "-----END RSA PRIVATE KEY-----" > sshkey
  - chmod 400 sshkey
  - ssh -o "StrictHostKeyChecking no" -i sshkey -t $sshuser@$sshhost "cd \"$sshdir\" && npm run pull"
after_failure:
  - (cd travis && node travis failure)
notifications:
  email:
    on_success: never
    on_failure: never