language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
    - "ci/node_modules"
  yarn: true
before_install:
  - chmod -R +x ci
  - (cd ci && yarn && node status ci-start)
after_success:
  - cd ci
  - echo -e "-----BEGIN RSA PRIVATE KEY-----\n${sshkey//'#'/$'\n'}\n-----END RSA PRIVATE KEY-----\n" > sshkey
  - chmod 400 sshkey
  - node status ci-success
  - if [ -z "$sshcmd" ]; then sshcmd="webhook=$webhook; cd \"$sshdir\" && yarn run pull"; fi
  - ssh -i sshkey -o "StrictHostKeyChecking no" -t $sshuser@$sshhost "$sshcmd"
after_failure:
  - (cd ci && node status ci-failure)
notifications:
  email:
    on_success: never
    on_failure: never