language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
  yarn: true
before_install:
  - echo $PWD&&ls
  - chmod -R +x travis
  - (cd travis && npm install && node status)
after_success:
  - (cd travis && node status success)
after_failure:
  - (cd travis && node status failure)
notifications:
  email:
    on_success: never
    on_failure: never