language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
    - "travis/node_modules"
  yarn: true
before_install:
  - echo $PWD&&ls
  - chmod -R +x travis
  - (cd travis && yarn && node travis)
after_success:
  - cd travis
  - echo -e "-----BEGIN RSA PRIVATE KEY-----\n${sshkey//'#'/$'\n'}\n-----END RSA PRIVATE KEY-----\n" > sshkey
  - chmod 400 sshkey
  - node travis success
  - if [ -z "$sshcmd" ]; then sshcmd="cd \"$sshdir\" && npm run pull"; fi
  - ssh -i sshkey -o "StrictHostKeyChecking no" -t $sshuser@$sshhost "$sshcmd"
after_failure:
  - (cd travis && node travis failure)
notifications:
  email:
    on_success: never
    on_failure: never