includes_dir: dynamic

# Compress CSS
sass:
    style: compressed

exclude: ["dynamic/", "Gemfile", "Gemfile.lock", "*node_modules*", "site/*webpack*.js", "site/*package.json*", "server/"]

url: https://injectify.samdd.me
logo: https://widgetbot.io/widgetbot.png

plugins:
  - jekyll-seo-tag
  - jekyll-git_metadata

jekyll_tidy:
  exclude: ["*.js"]

destination:     ../output